/*
 * D20-go
 *
 * Restful RNG/dice API built with OpenAPI 2.0 and Go
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"log"
	"net/http"
	sw "./go"
)

func main() {
	log.Printf("D20-go Server started")

	router := sw.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
