/*
 * D20-go
 *
 * Restful RNG/dice API built with OpenAPI 2.0 and Go
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type D12 struct {

	Roll int64 `json:"roll,omitempty"`
}
