/*
 * D20-go
 *
 * Restful RNG/dice API built with OpenAPI 2.0 and Go
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "D20-go")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/api/",
		Index,
	},

	Route{
		"D10Get",
		strings.ToUpper("Get"),
		"/api/d10",
		D10Get,
	},

	Route{
		"D12Get",
		strings.ToUpper("Get"),
		"/api/d12",
		D12Get,
	},

	Route{
		"D20Get",
		strings.ToUpper("Get"),
		"/api/d20",
		D20Get,
	},

	Route{
		"D4Get",
		strings.ToUpper("Get"),
		"/api/d4",
		D4Get,
	},

	Route{
		"D6Get",
		strings.ToUpper("Get"),
		"/api/d6",
		D6Get,
	},

	Route{
		"D8Get",
		strings.ToUpper("Get"),
		"/api/d8",
		D8Get,
	},
}
